### ISSUE TITLE
JUnit5 does not work with Eclipse 2020-06

### ISSUE THREAD

**Issue by sometowngeek** [eclipse/buildship#1006]
### Expected Behavior
In Eclipse, I am expecting the test to execute. This is the test class I have:
```java
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class MyTest {
	
	@Test
	void test() {
		Assertions.assertEquals(1, 1);
	}

}
```

My build.gradle has:
```groovy
plugins {
    id 'java-library'
    id 'maven-publish'
    id 'eclipse-wtp'
}
// ...
repositories {
    mavenCentral()
}

dependencies {
    // ...
    
    // JUnit5
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-api:5.5.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.5.0'
}

test {
    useJUnitPlatform()
}
```

### Current Behavior
I get the `java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener` exception.

### Context
I am trying to run tests using JUnit5 and it worked when I used Eclipse 2020-03, but does not work with 2020-06.

### Steps to Reproduce 
1. In build.gradle, set the test dependencies to: `org.junit.jupiter:junit-jupiter-api:5.4.2` and `org.junit.jupiter:junit-jupiter-engine:5.4.2`
2. Run the MyTest test.
2.a. Received exception: 
```
java.lang.NoClassDefFoundError: org/junit/platform/commons/PreconditionViolationException
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:75)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:66)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:53)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.PreconditionViolationException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
3. In build.gradle, set the test dependencies to: `org.junit.jupiter:junit-jupiter-api:5.5.0` and `org.junit.jupiter:junit-jupiter-engine:5.5.0`
4. Run the MyTest test.
4.a. Received exception: 
```
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener
	at org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder.getLauncherDiscoveryListener(LauncherDiscoveryRequestBuilder.java:241)
	at org.junit.platform.launcher.core.LauncherDiscoveryRequestBuilder.build(LauncherDiscoveryRequestBuilder.java:235)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:75)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:66)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:53)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineDiscoveryListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.EngineDiscoveryListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more
```

### Your Environment

Tool | Version
------------ | -------------
JDK |1.8.0_162
Gradle | 6.5.1
Eclipse | 2020-06

**Comment by sometowngeek** [comment]
Correction: It works with Eclipse Photon, not 2020-03.

**Comment by lukeu** [comment]
Is this due to #980, and if so, do one of the tips from https://github.com/eclipse/buildship/issues/980#issuecomment-661102992 onwards help?

**Comment by jcbritobr** [comment]
This is critical and was not fixed until now. :(

**Comment by sometowngeek** [comment]
Sorry for falling off the grid. I haven't had a chance to revisit this until now.

What I tried is updating the JUnit 5 version to 5.7.0 and it works now.

I think it was something with 5.4.2 and 5.5.0 that made JUnit testing difficult in Eclipse.

Not sure whether it is worth closing this issue. I didn't do regression testing with 5.7.0 yet.

**Comment by pedrolamarao** [comment]
I have this problem sometimes with Eclipse 2020-09, even with `junit-jupiter` 5.7.0 in the `testImplementation` configuration. It does not happen consistently: sometimes it happens, sometimes it doesn't. When it doesn't, Eclipse complains that no tests have been found.

**Comment by AndreBritoKD** [comment]
@pedrolamarao I have a similar problem with dependencies, gradle and tests. maybe it is related 
https://github.com/eclipse/buildship/issues/1053

**Comment by donat** [comment]
This is a known issue. You can use the workaround from here: https://github.com/eclipse/buildship/issues/980#issuecomment-665124002
