### ISSUE TITLE
decouple the JRE running Buildship (the IDE itself) from the JDK needed by the project

### ISSUE THREAD

**Issue by martinlippert** [eclipse/buildship#1147]
Usually people define a version of Gradle to be used with a project that fits the needs of the project and works nicely with the Java version that is used in the project. So there is a meaningful coupling between the Java version that is used in the project and the Java version that the Gradle version supports that is used by the projects build config.

Buildship introduces another coupling here, which is between the JRE that is used to run the IDE and the Gradle version that is configured in the project. This means that you need to run your IDE with a JDK that is supported by the Gradle version that is configured in the projects that you want to work on - which doesn't make a lot of sense for the user (I know that there are good technical reasons for this coupling).

Nevertheless, it would be great if Buildship could decouple this dependency and allow people to use the Gradle version that is configured in the project with the JDK that is configured for the project - independent of the JDK that is used to run the IDE itself.

More background;
The major Eclipse EPP packages ship nowadays with a JDK17 runtime embedded and run on this JDK17 by default. Importing a project that uses a Gradle version for its build that doesn't support JDK17 yet (for whatever reason) results in an exception being thrown by Buildship that looks like this:

```
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:189)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:170)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:156)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:277)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	...
```

A solution is, of course, to update the Gradle version that is used inside of the projects build config to a version that supports JDK17 (in this case) - or to configure the IDE to run on a JDK version that is already supported by the Gradle version that is configured in the project. Both solutions are not ideal and the out-of-the-box experience is not great.

I also expect the Eclipse packages to jump to a newer embedded JDK version relatively soon after the JDK got published, for example the next LTS version (JDK 21), which would result in most of the projects out there using Gradle would not import nicely into Eclipse at that time - until a new Gradle version appears that support JDK 21 and all projects upgrade to that Gradle version. So users will stumble upon this again and again.

Therefore I think it would be awesome if we could decouple those JDKs in when using Buildship.

**Comment by mickaelistria** [comment]
FWIW, some Eclipse projects are progressively making Java 17 a requirement (Corrosion already does, ShellWax might do it within a few hours/days, TM4E within a few weeks...), so the workaround of enforcing Java 11 to launch Eclipse IDE won't be working anymore.
The only solution for users would become to manually set different Gradle version for their project.

Couldn't BuildShip pick the latest known Gradle version by default anyway?
