### ISSUE TITLE
Buildship setup fails with RepositoryNotFoundException

### ISSUE THREAD

**Issue by FieteO** [eclipse/buildship#1149]
### Expected Behavior
Following the [Setup Instructions](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md), I should be able to install Eclipse in the Commiters Edition with the buildship project enabled.

### Current Behavior
After hitting install, the IDE launches but the buildship project is not opened and no setup tasks are executed. When going to **Help -> Perform Setup Tasks** a window with an internal error `org.eclipse.jgit.errors.RepositoryNotFoundException` pops up.

``` bash
Java.lang.Exception: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/fiete/Documents/development/buildship/git
	at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.isNeeded(GitCloneTaskImpl.java:861)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.initNeededSetupTasks(SetupTaskPerformer.java:2285)
	at org.eclipse.oomph.setup.ui.wizards.ConfirmationPage.initNeededSetupTasks(ConfirmationPage.java:355)
	at org.eclipse.oomph.setup.ui.wizards.ConfirmationPage.enterPage(ConfirmationPage.java:259)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard.pageChanged(SetupWizard.java:658)
	at org.eclipse.jface.wizard.WizardDialog$5.run(WizardDialog.java:1518)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.wizard.WizardDialog.firePageChanged(WizardDialog.java:1515)
	at org.eclipse.jface.wizard.WizardDialog.update(WizardDialog.java:1325)
	at org.eclipse.jface.wizard.WizardDialog.updateForPage(WizardDialog.java:1257)
	at org.eclipse.jface.wizard.WizardDialog.lambda$3(WizardDialog.java:1222)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1222)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:917)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:119)
	at org.eclipse.oomph.util.ReflectUtil.invokeMethod(ReflectUtil.java:149)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizardPage.gotoPage(SetupWizardPage.java:225)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizardPage.gotoNextPage(SetupWizardPage.java:207)
	at org.eclipse.oomph.setup.ui.wizards.VariablePage$6.run(VariablePage.java:699)
	at org.eclipse.oomph.ui.UIUtil$4.run(UIUtil.java:534)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5101)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4584)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard.openDialog(SetupWizard.java:776)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$Updater.openDialog(SetupWizard.java:1802)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$Updater.perform(SetupWizard.java:1818)
	at org.eclipse.oomph.setup.presentation.handlers.PerformHandler.run(PerformHandler.java:52)
	at org.eclipse.oomph.setup.presentation.handlers.AbstractDropdownItemHandler.execute(AbstractDropdownItemHandler.java:51)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /home/fiete/Documents/development/buildship/git
	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:627)
	at org.eclipse.jgit.api.Git.open(Git.java:93)
	at org.eclipse.jgit.api.Git.open(Git.java:73)
	at org.eclipse.oomph.setup.git.impl.GitCloneTaskImpl.isNeeded(GitCloneTaskImpl.java:819)
	... 79 more
```

This makes sense, since the repository was not cloned into that location:
``` bash
fiete@ubu:~/Documents/development/buildship$ tree -L 2
.
├── git
│   └── tooling-local.target
├── ide
│   └── eclipse
└── ws

4 directories, 1 file
```

### Context

I would like to be able to contribute to buildship. For that I need to install the Eclipse IDE to run the project and it's tests.

### Steps to Reproduce
I am following the [Setup Instructions](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md).
![1-eclipse-commiters](https://user-images.githubusercontent.com/41323592/163798369-23c2d484-f950-48b0-8747-0cb8c30c6e39.png)
![2-eclipse-projects](https://user-images.githubusercontent.com/41323592/163798379-96334313-c3b8-4dec-a486-0d846d67f424.png)
![3-variables](https://user-images.githubusercontent.com/41323592/163798388-de9ceb07-cb93-44ef-9a47-8c8715efe824.png)
![4-confirmation](https://user-images.githubusercontent.com/41323592/163798394-a896c7da-f495-456e-bc7a-138c327a2731.png)

Note that I have sped up the video, however I waited for enough time for any eventual automatic setup task to complete before opening that setup menu.

https://user-images.githubusercontent.com/41323592/163798620-af90cc66-6265-4257-920e-1146eb43e95b.mp4

### Your Environment
Ubuntu 20.04, openjdks 8 and 11 from the official repositories.

**Comment by FieteO** [comment]
I have now gave it a second shot, but this time by just accepting the installer defaults. The same issue occurs, but I then manually cloned the project into the appropriate folder:
``` bash
fiete@ubu:~/buildship-master/git$ ls buildship/
tooling-local.target
fiete@ubu:~/buildship-master/git$ mv buildship/tooling-local.target .
fiete@ubu:~/buildship-master/git$ rm -d buildship
fiete@ubu:~/buildship-master/git$ git clone https://github.com/eclipse/buildship.git
Cloning into 'buildship'...
...
fiete@ubu:~/buildship-master/git$ mv tooling-local.target buildship/
```
When I then run the setup tasks under **Help -> Perform Setup Tasks** everything goes through.
I then ran the tests with right clicking on `org.eclipse.buildship.core.test` **>> Run As >> JUnit Plug-In-Test**.

The tests fail however with
``` bash
org.spockframework.runtime.extension.ExtensionException: Duplicated Extension declaration for [org.spockframework.runtime.extension.builtin.IncludeExcludeExtension]
Source 1: bundleresource://46.fwk842676016:35/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Source 2: bundleresource://46.fwk842676016:18/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
This is most likely caused by having two different version of a library on the classpath.
	at org.spockframework.runtime.ExtensionClassesLoader.loadClasses(ExtensionClassesLoader.java:40)
	at org.spockframework.runtime.ExtensionClassesLoader.loadClassesFromDefaultLocation(ExtensionClassesLoader.java:31)
	at org.spockframework.runtime.RunContext.createBottomContext(RunContext.java:185)
	at org.spockframework.runtime.RunContext.get(RunContext.java:153)
	at org.spockframework.runtime.Sputnik.runExtensionsIfNecessary(Sputnik.java:90)
	at org.spockframework.runtime.Sputnik.getDescription(Sputnik.java:54)
	at org.junit.runners.model.RunnerBuilder.configureRunner(RunnerBuilder.java:81)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:72)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:74)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
Does it make sense to dig deeper here, or is this just the result of the initial setup not working properly?
Is my issue even properly addressed here, or does this Oomph-based installation of buildship have it's own repository where such issues with the setup should be addressed?
