### ISSUE TITLE
Oomph-based setup fails with exception

### ISSUE THREAD

**Issue by FieteO** [eclipse/buildship#1184]
### Expected Behavior
I am following the [Setup instructions](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md) for the Oomph-based setup.

### Current Behavior
The installation via the Eclipse Installer fails with the following exception:
```
Fetching content.xml.xz from https://download.eclipse.org/releases/2022-06/202206151000/
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:431)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:341)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:904)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3792)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1656836586776
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Eclipse JDT Core patch for Groovy 4.7.0.v202206301729-e2203 (org.codehaus.groovy.jdt.patch.feature.group 4.7.0.v202206301729-e2203) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.18.1100.v20220308-0310,3.18.1100.v20220308-0310]' but it could not be found
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1656836586776
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.eclipse.feature.feature.group 0.0.0
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Compilerless feature 4.7.0.v202206301729-e2203 (org.codehaus.groovy.compilerless.feature.feature.group 4.7.0.v202206301729-e2203)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.headless.feature.feature.group [4.7.0.v202206301729-e2203,4.7.0.v202206301729-e2203]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Eclipse Groovy Development Tools 4.7.0.v202206301729-e2203 (org.codehaus.groovy.eclipse.feature.feature.group 4.7.0.v202206301729-e2203)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.compilerless.feature.feature.group [4.7.0.v202206301729-e2203,4.7.0.v202206301729-e2203]
  ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
    ERROR: org.eclipse.equinox.p2.director code=0 From: Groovy-Eclipse Headless feature 4.7.0.v202206301729-e2203 (org.codehaus.groovy.headless.feature.feature.group 4.7.0.v202206301729-e2203)
    ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.codehaus.groovy.jdt.patch.feature.group [4.7.0.v202206301729-e2203,4.7.0.v202206301729-e2203]

Took 3 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

### Steps to Reproduce 

Follow the [setup instructions](https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md). These are my variables:
![variables](https://user-images.githubusercontent.com/41323592/177032053-ed3d4a8c-464e-4f71-b302-97f5f94a3a67.png)

### Your Environment

Windows 10

**Comment by fvclaus** [comment]
I also struggled with this error. I believe that you picked the "wrong" Eclipse version.  Currently the Oomph setup only supports one specific Eclipse version, depending on what is currently listed for the groovy-eclipse repository value.  See also https://github.com/groovy/groovy-eclipse/wiki#releases

**Comment by thomasdelhomenie** [comment]
I had the same issue, and I confirm that selecting the Product Version `2022-03` fixed it for me.
