### ISSUE TITLE
An internal error occurred during: "Install semantic highlighting".

### ISSUE THREAD

**Issue by quaff** [eclipse/buildship#1282]
Error occurs when open any .gradle.kts file
```
!ENTRY org.eclipse.core.jobs 4 2 2023-12-01 15:59:56.593
!MESSAGE An internal error occurred during: "Install semantic highlighting".
!STACK 1
Java Model Exception: Error in Java Model (code 969): cornerstone does not exist
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:550)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2567)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2445)
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2543)
	at org.jetbrains.kotlin.core.utils.ProjectUtils.getDependencyProjects(ProjectUtils.kt:116)
	at org.jetbrains.kotlin.core.utils.ProjectUtils.getDependencyProjects$default(ProjectUtils.kt:114)
	at org.jetbrains.kotlin.core.utils.ProjectUtils.getSourceFilesWithDependencies(ProjectUtils.kt:109)
	at org.jetbrains.kotlin.core.resolve.EclipseAnalyzerFacadeForJVM.analyzeScript(EclipseAnalyzerFacadeForJVM.kt:138)
	at org.jetbrains.kotlin.core.model.KotlinAnalysisFileCache.resolve(KotlinAnalysisFileCache.kt:45)
	at org.jetbrains.kotlin.core.model.KotlinAnalysisFileCache.getAnalysisResult(KotlinAnalysisFileCache.kt:32)
	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinSemanticHighlightingVisitor.computeHighlightingRanges(KotlinSemanticHighlightingVisitor.kt:41)
	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinSemanticHighlighter.reconcile(KotlinSemanticHighlighting.kt:103)
	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinSemanticHighlighter$install$2.invoke(KotlinSemanticHighlighting.kt:148)
	at org.jetbrains.kotlin.ui.editors.highlighting.KotlinSemanticHighlighter$install$2.invoke(KotlinSemanticHighlighting.kt:147)
	at org.jetbrains.kotlin.core.model.KotlinModelUtilsKt$runJob$job$1.run(kotlinModelUtils.kt:90)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
![1](https://github.com/eclipse/buildship/assets/143040/98302f5a-30bc-4514-a2a6-a6160161b330)

### Your Environment
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-09 (4.29.0)
Build id: 20230907-1323
Kotlin	0.8.24.v20220922-1405
Buildship	3.1.8.v20231120-0947

**Comment by oleosterhagen** [comment]
This stacktrace is not from Eclipse Buildship. It comes from [Kotlin Eclipse](https://github.com/Kotlin/kotlin-eclipse/). This is the relevant [issue tracker](https://youtrack.jetbrains.com/issues/KE).

When you are looking for Kotlin DSL editor support in Eclipse: This is installable as an incubating feature. Please check out the [announcement](https://discuss.gradle.org/t/buildship-3-1-8-is-now-available/47036/1).

@quaff Could you close this issue here?
