### ISSUE TITLE
Exception thrown using Gradle Import via oomph for a fresh install requiring a clone

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [eclipse/buildship#1319]
I have created an Oomph product and project to install Eclipse and configure it as required.

For a user doing a fresh install of this oomph config, the STARTUP tasks should firstly clone the git repository to a given location, and once cloned, the `Gradle Import` task should import all projects in that location.

### Expected Behavior
After initial install of the product, Oomph setup tasks begins shortly after Eclipse starts up, and works through all the STARTUP tasks, which includes cloning the Git repo to the machine because its not already there, then Gradle Imports the projects within that cloned repo.

### Current Behavior
The Oomph setup tasks dialog never appears. There is an error in the Eclipse .log file:

```
!ENTRY org.eclipse.oomph.setup.ui 4 0 2024-10-01 16:33:35.753
!MESSAGE Failed to compare project paths for equality
!STACK 0
java.io.UncheckedIOException: Failed to compare project paths for equality
	at org.eclipse.buildship.oomph.impl.CustomGradleImportTaskImpl.calculateProjectsToImport(CustomGradleImportTaskImpl.java:104)
	at org.eclipse.buildship.oomph.impl.CustomGradleImportTaskImpl.isNeeded(CustomGradleImportTaskImpl.java:54)
	at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.initNeededSetupTasks(SetupTaskPerformer.java:2285)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:811)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin$1$1.run(SetupUIPlugin.java:266)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.file.NoSuchFileException: /Users/marklawrence/gitRepos/<org>/<repo name>
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.isSameFile(UnixFileSystemProvider.java:343)
	at java.base/java.nio.file.Files.isSameFile(Files.java:1531)
	at org.eclipse.buildship.oomph.impl.CustomGradleImportTaskImpl.calculateProjectsToImport(CustomGradleImportTaskImpl.java:99)
	... 5 more
```

This is clearly happening because `isNeeded()` is looking for projects to import to decide if it needs to run, however it is looking at a folder location that doesn't exist yet as the Git clone task hasn't ran yet. Could it assume that it 'is needed' if no folder is currently found?

### Context
I can't really use the gradle import task as part of STARTUP tasks after first install, combined with needing to clone the repository containing the projects first.

I've tried using the ResourceCreationTask to create a dummy file in the location, which does cause the Oomph setup tasks dialog to appear, however the Git clone task then fails with an error as it finds a folder it doesn't recognise as a git repository.

### Steps to Reproduce 
Self-explanatory

### Your Environment
Eclipse 4.23
Installing buildship oomph plugins from https://download.eclipse.org/buildship/updates/e411/releases/3.x/3.1.5.v20210113-0909/

**Comment by Mark-J-Lawrence** [comment]
I've managed to work around this......previously the `.project` & `.settings/` files weren't committed to the repo, so the gradle import worked out it was a gradle nature......If I now save these to the repo, I can now simply use the Ooomph project imports and no longer need to use the Gradle import task.

**Comment by Mark-J-Lawrence** [comment]
I've come back to this - The above work around isn't great. What I really want is for the Gradle Import to work, and it then automatically synchronises, obtaining all the required dependencies.

**Comment by Mark-J-Lawrence** [comment]
The problem is [this code](https://github.com/eclipse-buildship/buildship/blob/218322a0d994543cf0aec77def05e6feeddd4b95/org.eclipse.buildship.oomph/src/main/java/org/eclipse/buildship/oomph/impl/CustomGradleImportTaskImpl.java#L53-L55)

how should this code work when Oomph is being used for a totally fresh install, where the clone of the repo containing all the projects hasn't happened yet etc

**Comment by Mark-J-Lawrence** [comment]
See comments in https://github.com/eclipse-buildship/buildship/pull/1361 - this is happening because we've made our Oomph setup not install into the workspace - I'm happy we're doing something a bit niche, and we've since worked around it. Closing.
