### ISSUE TITLE
Log4 warning message printed to console upon Eclipse startup

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#349]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509038

**Comment by moberhuber** [comment]
I still see the warning printed on startup with eclipse-committers-oxygen-RC1-linux-gtk-x86_64:

  log4j:WARN No appenders could be found for logger   (com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions).
  log4j:WARN Please initialize the log4j system properly.

This doesn't look good for Eclipse. I suspect the root cause might be, that I'm sitting behind an authenticating proxy with no access to the Internet. When I launch Eclipse and look at the Errorlog view, I also see this:

WARNING: Could not load Gradle version information
org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.
	at com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:175)
	at com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:159)
	at com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions.create(PublishedGradleVersions.java:119)
	at org.eclipse.buildship.core.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.gradleware.tooling.toolingutils.distribution.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:172)
	... 4 more

**Comment by moberhuber** [comment]
I could also reproduce the "log4j:WARN No appenders could be found for logger "
 on a RHEL 6.3 host with full Internet access.

So the "Could not load Gradle version" is a separate issue, and  I reported #483 for it. Please continue investigating the "log4j:WARN" issue on this ticket. See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=517319 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=358968 for related background information.
