### ISSUE TITLE
Message "absent persistent model" prevents closing eclipse workspace

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#404]
[Original report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=512701) from Johannes Roeder 

I have Buildship 2.0.1 installed, and I started to get the message "Absent persistent model" when trying to close/restart eclipse.
Essentially I can only close eclipse by killing the process from task manager.

I found the following snippet in the eclipse logfile (I hope I kept the relevant pieces):

!ENTRY org.eclipse.ui.workbench 4 2 2017-02-24 16:21:38.204
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.IllegalStateException: Absent persistent model
	at org.eclipse.buildship.core.preferences.internal.AbsentPersistentModel.getBuildDir(AbsentPersistentModel.java:47)
	at org.eclipse.buildship.core.preferences.internal.PersistentModelConverter.toProperties(PersistentModelConverter.java:46)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.persistPrefsChecked(DefaultModelPersistence.java:156)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.persistPrefs(DefaultModelPersistence.java:142)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.persistAllProjectPrefs(DefaultModelPersistence.java:136)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.onEvent(DefaultModelPersistence.java:92)
	at org.eclipse.buildship.core.event.internal.DefaultListenerRegistry.dispatch(DefaultListenerRegistry.java:53)
	at org.eclipse.buildship.ui.workspace.ShutdownListener.preShutdown(ShutdownListener.java:26)
(...)

Any idea on what is happening?

**Comment by donat** [comment]
This seems like a bug in Buildship synchronization, thank you very much for reporting! I'll try to fix it very soon.

**Comment by donat** [comment]
Commit with the fix: https://github.com/eclipse/buildship/commit/6f3eb578a4d0289297c8069aaeb6379a0366ff80
