### ISSUE TITLE
Executing task eclipseFactorypath with Buildship gives exception

### ISSUE THREAD

**Issue by vogella** [eclipse/buildship#432]
To validate:

Clone https://github.com/traggatt/AptTest
Import project into Eclipse
Run eclipseJdtApt via Buildship -> works
Run eclipseFactorypath via Buildship -> fails

![image](https://cloud.githubusercontent.com/assets/139910/24195547/7b31a048-0efa-11e7-9bbb-2f2c96865b95.png)

Exception: 
org.eclipse.buildship.core.GradlePluginsRuntimeException: Cannot execute command 'org.eclipse.buildship.ui.commands.runtasks'.
	at org.eclipse.buildship.ui.view.task.TreeViewerDoubleClickListener.run(TreeViewerDoubleClickListener.java:56)
	at org.eclipse.buildship.ui.view.task.TreeViewerDoubleClickListener.doubleClick(TreeViewerDoubleClickListener.java:44)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:831)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:828)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1459)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1258)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:247)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:306)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5240)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4510)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4095)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1146)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1035)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: org.eclipse.e4.core.di.InjectionException: org.eclipse.buildship.core.GradlePluginsRuntimeException: Cannot read preference from file /home/vogella/git/AptTest/aptProject/.settings/org.eclipse.buildship.core.prefs
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:390)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:377)
	at org.eclipse.buildship.ui.view.task.TreeViewerDoubleClickListener.run(TreeViewerDoubleClickListener.java:54)
	... 38 more
Caused by: org.eclipse.buildship.core.GradlePluginsRuntimeException: Cannot read preference from file /home/vogella/git/AptTest/aptProject/.settings/org.eclipse.buildship.core.prefs
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$PropertiesFilePreferenceStore.loadProperties(PreferenceStore.java:155)
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$PropertiesFilePreferenceStore.getProperties(PreferenceStore.java:143)
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$PropertiesFilePreferenceStore.read(PreferenceStore.java:169)
	at org.eclipse.buildship.core.configuration.internal.DefaultProjectConfigurationPersistence.readProjectConfiguration(DefaultProjectConfigurationPersistence.java:56)
	at org.eclipse.buildship.core.configuration.internal.DefaultProjectConfigurationPersistence.loadFromPropertiesFile(DefaultProjectConfigurationPersistence.java:67)
	at org.eclipse.buildship.core.configuration.internal.DefaultProjectConfigurationPersistence.readProjectConfiguration(DefaultProjectConfigurationPersistence.java:43)
	at org.eclipse.buildship.core.configuration.internal.DefaultProjectConfigurationManager.tryReadProjectConfiguration(DefaultProjectConfigurationManager.java:112)
	at org.eclipse.buildship.core.configuration.internal.DefaultProjectConfigurationManager.readProjectConfiguration(DefaultProjectConfigurationManager.java:101)
	at org.eclipse.buildship.ui.view.task.TaskNodeSelectionUtils.getFixedRequestAttributes(TaskNodeSelectionUtils.java:115)
	at org.eclipse.buildship.ui.view.task.TaskNodeSelectionUtils.getFixedRequestAttributes(TaskNodeSelectionUtils.java:103)
	at org.eclipse.buildship.ui.view.task.TaskNodeSelectionUtils.getRunConfigurationAttributes(TaskNodeSelectionUtils.java:75)
	at org.eclipse.buildship.ui.view.task.BaseRunConfigurationHandler.getRunConfigurationAttributes(BaseRunConfigurationHandler.java:30)
	at org.eclipse.buildship.ui.view.task.RunTasksHandler.execute(RunTasksHandler.java:32)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 48 more
Caused by: java.io.FileNotFoundException: /home/vogella/git/AptTest/aptProject/.settings/org.eclipse.buildship.core.prefs (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$PropertiesFilePreferenceStore.loadProperties(PreferenceStore.java:151)
	... 66 more

**Comment by oehme** [comment]
The example works just fine for me. The exception looks like the .settings folder was deleted.

**Comment by vogella** [comment]
Now also works for me, with the same steps. Good old deterministic machines. ;-)

Thanks @oehme, sorry for the noise.
