### ISSUE TITLE
Eclipse UI frozen for 20 minutes (updating the Execution Tree?)

### ISSUE THREAD

**Issue by lukeu** [eclipse/buildship#439]
From the Gradle Tasks view I executed the 'buildNeeded' task (on project which depends on about 5 others). This takes about 40s to run from clean on the Gradle command line. 

After a short while (a minute or so?) the Eclipse UI became completely frozen for over 20 minutes.

This task will have invoked around 15,000 unit tests. It seems to be a scalability issue with updating the Gradle Executions view.

I checked at 5 minute intervals, and all 3 times the main thread was stuck at:

    "main" #1 prio=6 os_prio=0 tid=0x02dad400 nid=0x91c runnable [0x0018e000]
    java.lang.Thread.State: RUNNABLE
        at org.eclipse.core.internal.databinding.identity.IdentityObservableSet.retainAll(IdentityObservableSet.java:165)
        at org.eclipse.core.internal.databinding.property.value.DelegatingCache.retainAll(DelegatingCache.java:186)
        at org.eclipse.core.internal.databinding.property.value.SetDelegatingValueObservableMap$1.handleSetChange(SetDelegatingValueObservableMap.java:149)
        at org.eclipse.core.databinding.observable.set.SetChangeEvent.dispatch(SetChangeEvent.java:69)
        at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:117)
        at org.eclipse.core.databinding.observable.set.DecoratingObservableSet.fireSetChange(DecoratingObservableSet.java:70)
        at org.eclipse.core.databinding.observable.set.DecoratingObservableSet.handleSetChange(DecoratingObservableSet.java:112)
        at org.eclipse.core.databinding.observable.set.DecoratingObservableSet$1.handleSetChange(DecoratingObservableSet.java:85)
        at org.eclipse.core.databinding.observable.set.SetChangeEvent.dispatch(SetChangeEvent.java:69)
        at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:117)
        at org.eclipse.core.databinding.observable.set.ObservableSet.fireSetChange(ObservableSet.java:74)
        at org.eclipse.core.internal.databinding.observable.masterdetail.DetailObservableSet.access$2(DetailObservableSet.java:1)
        at org.eclipse.core.internal.databinding.observable.masterdetail.DetailObservableSet$1.handleSetChange(DetailObservableSet.java:53)
        at org.eclipse.core.databinding.observable.set.SetChangeEvent.dispatch(SetChangeEvent.java:69)
        at org.eclipse.core.databinding.observable.ChangeManager.fireEvent(ChangeManager.java:117)
        at org.eclipse.core.databinding.observable.set.ObservableSet.fireSetChange(ObservableSet.java:74)
        at org.eclipse.core.databinding.observable.set.WritableSet.add(WritableSet.java:96)
        at org.eclipse.core.internal.databinding.observable.masterdetail.DetailObservableSet.add(DetailObservableSet.java:150)
        at org.eclipse.jface.internal.databinding.viewers.ObservableCollectionTreeContentProvider.getOrCreateNode(ObservableCollectionTreeContentProvider.java:259)
        at org.eclipse.jface.internal.databinding.viewers.ObservableCollectionTreeContentProvider.getChildren(ObservableCollectionTreeContentProvider.java:201)
        at org.eclipse.jface.internal.databinding.viewers.ObservableCollectionTreeContentProvider.getChildren(ObservableCollectionTreeContentProvider.java:194)
        at org.eclipse.jface.databinding.viewers.ObservableListTreeContentProvider.getChildren(ObservableListTreeContentProvider.java:232)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isParentMatch(PatternFilter.java:250)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isElementVisible(PatternFilter.java:236)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.computeAnyVisible(PatternFilter.java:141)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isAnyVisible(PatternFilter.java:124)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isParentMatch(PatternFilter.java:253)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isElementVisible(PatternFilter.java:236)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.computeAnyVisible(PatternFilter.java:141)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isAnyVisible(PatternFilter.java:124)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isParentMatch(PatternFilter.java:253)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isElementVisible(PatternFilter.java:236)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.computeAnyVisible(PatternFilter.java:141)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isAnyVisible(PatternFilter.java:124)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isParentMatch(PatternFilter.java:253)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.isElementVisible(PatternFilter.java:236)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.select(PatternFilter.java:148)
        at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:56)
        at org.eclipse.buildship.ui.external.viewer.PatternFilter.filter(PatternFilter.java:93)
        at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:911)
        at org.eclipse.jface.viewers.AbstractTreeViewer.getSortedChildren(AbstractTreeViewer.java:621)
        at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$0(AbstractTreeViewer.java:817)
        at org.eclipse.jface.viewers.AbstractTreeViewer$$Lambda$58/12054367.run(Unknown Source)
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
        at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:795)
        at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:596)
        at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:766)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1636)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1633)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1633)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1633)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1633)
        at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1069)
        at org.eclipse.buildship.ui.view.execution.ExecutionProgressListener$1.run(ExecutionProgressListener.java:138)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        - locked <0x2ef022a8> (a org.eclipse.swt.widgets.RunnableLock)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    Locked ownable synchronizers:
         - None

Note that I had typed a filter into the Gradle Execution view, which seems to be a requirement for the _complete_ freeze up.

I have repeated the issue without the filter set, and while the Eclipse UI is not completely frozen I would call it "frustratingly unresponsive" - repeatedly freezing for periods of ~4s or so every 10s. (The freezes don't appear to be related to GCs, in case you're wondering.) I left the task running for 15 minutes - so it looks like it may take a similar length of time to complete anyway. Note I have the Gradle Execution view minimized. Then I closed it and the Gradle build task "suddenly" completed (as seen in the console view).

**Comment by lukeu** [comment]
Versions of things:

 * Buildship v2.0.0
 * Eclipse Neon.3 (32-bit)
 * JDK 8 u92 (32-bit)
 * Windows 7 (64-bit)

**Comment by oehme** [comment]
Thanks for the report @lukeu. This is a known issue with the execution view, which redraws on every event, creating massive pressure on the UI thread. I guess it's time to insert some kind of batching here.

**Comment by lukeu** [comment]
Köszi szépen!

**Comment by donat** [comment]
Szívesen! :)
