### ISSUE TITLE
Eclipse doesn't start with a lot of buildship errors

### ISSUE THREAD

**Issue by regrog** [eclipse/buildship#481]
I'm not sure why this is happening, but today my eclipse can't start using my usual workspace. I'm getting many errors from buildship in log file and the eclipse shuts down without showing the UI.
Eclipse Oxygen Release Milestone 7 (4.7.0 M7) Build id: 20170519-0031
Buildship 2.0.2.v20170420-0909
Gradle 3.5
java 1.8.0_131

I recently installed Jboss tools in my eclipse but I worked just fine for many hours so I don't think that's the problem.
It's something about the workspace because other workspaces don't have the issue.
I tryed to start eclipse with -clean parameter but the problem persists.

I'm sorry but I can't provide the plugins from my workspace.

These are the stack trace from eclipse .log file.
but not all the errors on the log, but only buildship's,  however buildship errors are the first to be logged, see attached file for the complete log. [error.zip](https://github.com/eclipse/buildship/files/1028344/error.zip)
```
!ENTRY org.eclipse.core.jobs 4 2 2017-05-25 09:31:40.919
!MESSAGE An internal error occurred during: "Load persistent model for all projects".
!STACK 0
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence$2.run(DefaultModelPersistence.java:189)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.NullPointerException
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.preferencesFile(DefaultModelPersistence.java:171)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.doLoadModel(DefaultModelPersistence.java:121)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence.access$000(DefaultModelPersistence.java:54)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence$1.load(DefaultModelPersistence.java:63)
	at org.eclipse.buildship.core.preferences.internal.DefaultModelPersistence$1.load(DefaultModelPersistence.java:59)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 5 more

!ENTRY org.eclipse.core.jobs 4 2 2017-05-25 09:31:40.920
!MESSAGE An internal error occurred during: "Initializing Java Tooling".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.buildship.core.CorePlugin.modelPersistence(CorePlugin.java:307)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerUpdater.updateFromStorage(GradleClasspathContainerUpdater.java:161)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.updateFromStorage(GradleClasspathContainerInitializer.java:65)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.loadClasspath(GradleClasspathContainerInitializer.java:49)
	at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.initialize(GradleClasspathContainerInitializer.java:39)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3076)
	at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:2982)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3022)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2040)
	at org.eclipse.jdt.core.JavaCore.initializeAfterLoad(JavaCore.java:4259)
	at org.eclipse.jdt.internal.ui.InitializeAfterLoadJob$RealJob.run(InitializeAfterLoadJob.java:36)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.eclipse.ui.workbench 4 2 2017-05-25 09:31:41.447
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.buildship.stsmigration.StsMigrationService.shouldDisplayNotification(StsMigrationService.java:46)
	at org.eclipse.buildship.stsmigration.StsMigrationService.run(StsMigrationService.java:32)
	at org.eclipse.buildship.stsmigration.Startup.earlyStartup(Startup.java:25)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:77)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2747)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

!ENTRY org.eclipse.ui 4 0 2017-05-25 09:31:41.449
!MESSAGE Unable to execute early startup code for the org.eclipse.ui.IStartup extension contributed by the 'org.eclipse.buildship.stsmigration' plug-in.
!STACK 0
java.lang.NullPointerException
	at org.eclipse.buildship.stsmigration.StsMigrationService.shouldDisplayNotification(StsMigrationService.java:46)
	at org.eclipse.buildship.stsmigration.StsMigrationService.run(StsMigrationService.java:32)
	at org.eclipse.buildship.stsmigration.Startup.earlyStartup(Startup.java:25)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:77)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:53)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$40.run(Workbench.java:2747)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by donat** [comment]
We'll investigate this problem shortly. In the meanwhile, could you please delete the `/.metadata/.plugins/org.eclipse.buildship.core` folder from your workspace location and then start Eclipse?

**Comment by regrog** [comment]
Done but nothing changed.
It seems that only deleting /.metadata/.plugins/org.eclipse.e4.workbench fix the issue but that action resets all workspace preferences about perspectives and views.
I know I won't lose anything, just want to notify this problem, I can keep working ;)

**Comment by regrog** [comment]
I created a new workspace without any project, I set up my usual perspectives and view but after a restart eclipse fails to start...
It's nothing to do with buildship ... I think there's a problem with jboss tool even if I only installed.
In this workspace I didn't import any project or server...
If you want to investigate on buildship stack trace, do it, but I'm going to investigate against jboss.
Thanks

**Comment by donat** [comment]
Thanks. There's a similar problem reported already (#454), so I'll investigate the problem anyway.

**Comment by rubensa** [comment]
It might be related with Eclipse preferences not been accessed in a thread-safe way.  See https://bugs.eclipse.org/bugs/show_bug.cgi?id=444188#c6
