### ISSUE TITLE
NullPointerException in GradleWorkbenchPreferencePage.performOk

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#527]
[Bugzilla report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=519680) from Andreas Sewe:
```
Hi Buildship team,

I've just been browsing through all the automated error reports that are new since Oxygen.0 (i.e., which never occurred before) and this NPE caught my attention:

Message: java.lang.NullPointerException
java.lang.NullPointerException: null
    at org.eclipse.buildship.ui.preferences.GradleWorkbenchPreferencePage.performOk(GradleWorkbenchPreferencePage.java:83)
    at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:902)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
    at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:886)
    at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:400)
    at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.okPressed(WorkbenchPreferenceDialog.java:168)
    at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:230)
    at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
    at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)



Bundles:
| org.eclipse.buildship.ui | 2.1.0.v20170711-1519 | 2.1.0.v20170711-1519 |
| org.eclipse.core.runtime | 3.13.0.v20170207-1030 | 3.13.0.v20170207-1030 |
| org.eclipse.jface | 3.13.0.v20170503-1507 | 3.13.0.v20170503-1507 |
| org.eclipse.swt | 3.106.0.v20170608-0516 | 3.106.0.v20170608-0516 |
| org.eclipse.ui | 3.109.0.v20170411-1742 | 3.109.0.v20170411-1742 |

Operating Systems:
| Windows | 6.1.0 | 10.0.0 |


The above information is a snapshot of the collected data. Visit https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/596549c1e4b014af93bb0917 for the latest data.

Thank you for your assistance.
 Your friendly error-reports-inbox.

---

(In reply to EPP Error Reports from comment #0)
> I've just been browsing through all the automated error reports that are new
> since Oxygen.0 (i.e., which never occurred before) ...

FYI, it's really easy to filter error reports in AERI, e.g., if you want to focus on just the problems introduced recently [1].

[1] <https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/?c:!((t:product-namespace,ns:org.eclipse,st:!t,min:%274.7.0.I20170612-0950%27),(t:project,op:contains_any_of,val:!(buildship))),sort:!((prop:numberOfReporters,dir:DESCENDING))>

```

**Comment by donat** [comment]
I can't reproduce the problem and the [code in question](https://github.com/eclipse/buildship/blob/9e950ecb7d8728d1252267a24f31060769f7538c/org.eclipse.buildship.ui/src/main/java/org/eclipse/buildship/ui/preferences/GradleWorkbenchPreferencePage.java#L83) seems fine to me.

**Comment by donat** [comment]
I did some digging in AERI. It seems like that the same problem is [reported many times](https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/incidents/?c:!((t:problem-id,val:'591db82fe4b07840a0436a57')),sort:!((prop:timestamp,dir:DESCENDING))) for different plugins. Browsing through the reports I found two things:
- The eclipse version is always the same: `4.7.0.I20170612-0950`
- Only external plugins produced this error, no report was done for the platform preferences.

**Comment by donat** [comment]
I reported the possible platform issue on [Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=520367).
