### ISSUE TITLE
 java.lang.IllegalArgumentException on everything after upgrading to Buildship 2.1.1 

### ISSUE THREAD

**Issue by wodencafe** [eclipse/buildship#528]
Hello all,

after upgrading from Buildship 2.0.2 where everything was working fine with our Multi Project Build, now that we have upgraded to 2.1.1, we see the following error pop up when doing ANYTHING:

An error has occurred. See error log for more details.
java.lang.IllegalArgumentException

![illegal_argument_exception png](https://user-images.githubusercontent.com/9727493/28280837-b237dcc8-6aea-11e7-9c95-d92d0fb93d4c.jpg)

This happens when clicking any project or any files, or interacting with any buildship project at all.

What is the deal with this? This was all working before upgrading to this version of buildship.

I have attached the Stack Trace from the Eclipse Error Log.

[eclipse_exceptions.txt](https://github.com/eclipse/buildship/files/1153448/eclipse_exceptions.txt)

https://bugs.eclipse.org/bugs/show_bug.cgi?id=519775

**Comment by donat** [comment]
@wodencafe Can you please try re-importing your projects with the Gradle import wizard?

**Comment by oehme** [comment]
@donat even if a reimport helps, such an error shouldn't start happening just because the user upgraded. We need to find out what happened there. 

Looking at the stacktrace, our classpath container should not throw exceptions, but just remain unchanged and log an error.

**Comment by wodencafe** [comment]
Hi @donat, so as it turns out, the error went away after I closed and re-opened all of the projects.
But it was very bizarre, the projects themselves were not actually showing as Closed until I restarted Eclipse.

Anyway I just wanted to bring this issue to the buildship team's attention in case  it happens to anyone else.

**Comment by donat** [comment]
@oehme I only wanted to enable @wodencafe to work and to make sure that it's not due to the classpath issue in #519. I'll definitely investigate for the next bugfix release.

**Comment by wodencafe** [comment]
Even though I'm not getting the pop up "IllegalArgumentException" every time I click something now, it still happens when I try to "Gradle Refresh" in Buildship

![illegal](https://user-images.githubusercontent.com/9727493/28321953-4c811f24-6b9a-11e7-8701-36fa1275b7f7.png)
:

```
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.loadBuildConfiguration(DefaultConfigurationManager.java:68)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.loadProjectConfiguration(DefaultConfigurationManager.java:110)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$3.apply(SynchronizeGradleBuildOperation.java:157)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$3.apply(SynchronizeGradleBuildOperation.java:153)
	at com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:267)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:229)
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:609)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.getOpenWorkspaceProjectsRemovedFromGradleBuild(SynchronizeGradleBuildOperation.java:161)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:120)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by donat** [comment]
@wodencafe For the first look the code seems fine. Can you please share some information about your project structure? I'm interested in the following:
- the root and one sub project location
- the content of the `.settings/org.eclipse.buildship.core.prefs` file content under the root and sub project

**Comment by donat** [comment]
I can't reproduce the issue locally.

**Comment by cdietrich** [comment]
we have the same problem with xtext

```
java.lang.IllegalArgumentException
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:77)
    at org.eclipse.buildship.core.util.file.RelativePathUtils.getAbsolutePath(RelativePathUtils.java:59)
    at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.relativePathToProjectRoot(DefaultConfigurationManager.java:213)
    at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.loadProjectConfiguration(DefaultConfigurationManager.java:109)
    at org.eclipse.buildship.core.workspace.internal.DefaultGradleWorkspaceManager.getGradleBuild(DefaultGradleWorkspaceManager.java:65)
    at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.loadClasspath(GradleClasspathContainerInitializer.java:52)
    at org.eclipse.buildship.core.workspace.internal.GradleClasspathContainerInitializer.initialize(GradleClasspathContainerInitializer.java:39)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:3071)
    at org.eclipse.jdt.internal.core.JavaModelManager$10.run(JavaModelManager.java:2977)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
    at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
    at org.eclipse.jdt.internal.core.JavaModelManager.initializeAllContainers(JavaModelManager.java:3017)
    at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:2038)
    at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3497)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2687)
    at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2851)
    at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:1956)
    at org.eclipse.jdt.internal.core.DeltaProcessingState.getRootInfos(DeltaProcessingState.java:310)
    at org.eclipse.jdt.internal.core.DeltaProcessingState.initializeRoots(DeltaProcessingState.java:255)
    at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2122)
    at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:473)
    at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
    at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
    at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
    at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:138)
    at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

and here is our prefs

```
dietrich-virtual-machine:.settings[master] dietrich$ cat org.eclipse.buildship.core.prefs 
connection.gradle.distribution=GRADLE_DISTRIBUTION(WRAPPER)
connection.project.dir=/home/dietrich/xtext-master3/git/xtext-umbrella/releng/gradle-composite
project.path=\:org.eclipse.xtext
```

i assume it is wrong to have an absolute path

**Comment by donat** [comment]
Thanks, @cdietrich! Yes, the project path should be always relative to the root project and should be an empty string for the root.

**Comment by cdietrich** [comment]
hmm why was it working before?

**Comment by oehme** [comment]
I think it would be reasonable for us to be backwards compatible here. If the path is already absolute, just keep it (and update it to relative when syncing next time).

**Comment by wodencafe** [comment]
We are still unable to Gradle Refresh our projects in Eclipse with Buildship :(

For example, we have a flat build structure, containing our application projects and a master directory, where all of the shared build logic is.

```
L-Application
L-Master
```

When refreshing the Application project, we see this error:
```
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.loadBuildConfiguration(DefaultConfigurationManager.java:68)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.loadProjectConfiguration(DefaultConfigurationManager.java:110)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$3.apply(SynchronizeGradleBuildOperation.java:157)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$3.apply(SynchronizeGradleBuildOperation.java:153)
	at com.google.common.collect.Iterators$6.computeNext(Iterators.java:617)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:267)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:229)
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:609)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.getOpenWorkspaceProjectsRemovedFromGradleBuild(SynchronizeGradleBuildOperation.java:161)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:120)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

```
These are the contents of the org.eclipse.buildship.core.prefs file:
```
connection.project.dir=
```

**Comment by donat** [comment]
Interesting, the prefs file content should be `connection.project.dir=../Master` for the `Application` module.

**Comment by donat** [comment]
Sry, the `was:implemented` tag is only intended for the absolute path pull request (#533).

**Comment by donat** [comment]
FTR the original problem is likely to happen because of #535.

**Comment by typekpb** [comment]
I've seen the similar stacktrace on linux system, once having 

    connection.project.dir=..\\XYZ

where XYZ is the root project. Fix was for me to replace it with:

    connection.project.dir=../XYZ
