### ISSUE TITLE
Buildship 2 does not sort properties in org.eclipse.buildship.core.prefs

### ISSUE THREAD

**Issue by mauromol** [eclipse/buildship#548]
After reimporting from scratch (with Import Existing Gradle Project) a multiproject that was already set up with Buildship 2, I see that all my projects now have changes to their `org.eclipse.buildship.core.prefs` files:
- a new commented time stamp is printed in the first line (which I suppose will change on every import attempt)
- properties are in random order

On the contrary, looking at my Buildship 1 projects it seems like properties are listed in alphabetical order and I can't remember their content changing on every import. Also I see no leading timestamp in them.

This is an issue when you share those prefs files in SCM (as we do).

**Comment by oehme** [comment]
What might have happened here is that our fallback storage implementation kicked in because the properties file was not accessible through the Eclipse preference API for whatever reason. That fallback implementation uses Java's Properties class, which would explain the timestamp.

We already had that fallback in Buildship 1 though. Is this problem reproducible?

**Comment by mauromol** [comment]
> Is this problem reproducible?

I just tried to remove all projects from the workspace (without deleting them from disk) and import them again with the Buildship import wizard. It happened again: the leading timestamp in each project `org.eclipse.buildship.core.prefs` file has been updated and some changes in the order of entries has been performed (the position of `connection.gradle.distribution` and `project.path` properties were swapped).

I didn't do anything else than removing and importing again.
Please note I'm using Gradle 4.1 with Buildship 2.1.1.v20170713-0944.

**Comment by donat** [comment]
@mauromol Can you please give the latest snapshot a try?

**Comment by mauromol** [comment]
Hi Donat, I tried this with Buildship 2.2.1.v20180108-2312-s and I now find entries in {{org.eclipse.buildship.core.prefs}} sorted in alphabetical order and without any leading timestamp, so I would say this has actually been fixed, thank you! 👍 

When do you plan to release 2.2.1 final version?

**Comment by donat** [comment]
Thanks for checking! The plan is to publish 2.2.1 early next week.

**Comment by mauromol** [comment]
By the way, I just tried another thing, I don't know if it's related.

I tested this fix by importing a multiproject with plain layout.
The master project also contains a buildSrc project. This buildSrc project was not imported by "Import Existing Gradle Project" wizard, but this was somewhat expected (after all, this buildSrc project is not part of the multiproject).
Then I decided to do a "Import Existing Projects Into Workspace" to carry in that missing buildSrc project into the workspace. And I got this exception:

```
org.eclipse.buildship.core.GradlePluginsRuntimeException: Cannot store preferences in project buildSrc in node org.eclipse.buildship.core.
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$ProjectScopeEclipsePreferencesPreferenceStore.flush(PreferenceStore.java:167)
	at org.eclipse.buildship.core.configuration.internal.BuildConfigurationPersistence.saveRootDirPreference(BuildConfigurationPersistence.java:164)
	at org.eclipse.buildship.core.configuration.internal.BuildConfigurationPersistence.savePathToRoot(BuildConfigurationPersistence.java:91)
	at org.eclipse.buildship.core.configuration.internal.DefaultConfigurationManager.saveProjectConfiguration(DefaultConfigurationManager.java:141)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:175)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: org.osgi.service.prefs.BackingStoreException: Exception occurred while saving project preferences: /buildSrc/.settings/org.eclipse.buildship.core.prefs.
	at org.eclipse.core.internal.resources.ProjectPreferences.save(ProjectPreferences.java:670)
	at org.eclipse.core.internal.preferences.EclipsePreferences.internalFlush(EclipsePreferences.java:431)
	at org.eclipse.core.internal.resources.ProjectPreferences.flush(ProjectPreferences.java:365)
	at org.eclipse.buildship.core.configuration.internal.PreferenceStore$ProjectScopeEclipsePreferencesPreferenceStore.flush(PreferenceStore.java:165)
	... 16 more
```

The project was imported though, but instead of seeing "Project and External Dependencies" container, I see an empty container named "org.eclipse.buildship.core.gradleclasspahtcontainer" container and (of course) compilation errors. Right-click => Refresh Gradle project on the buildSrc project fixes the problem.
However, it's not the first time I have to perform this path ("import existing projects into workspace" => Buildship exception about not being able to store preferences file => Refresh Gradle Project to fix it), so I don't know if this is somewhat related to this fix or not.

**Comment by donat** [comment]
Probably not, because we only adjusted the way how we write into the file stream. Nonetheless, I'll look into it.

**Comment by donat** [comment]
#638 is probably the root cause.

**Comment by mauromol** [comment]
Thank you, I'll track it!

**Comment by donat** [comment]
@mauromol The fix is available in the latest snapshot.
