### ISSUE TITLE
Cannot import Gradle Project with Buildship Wizard

### ISSUE THREAD

**Issue by christopherbryanboyd** [eclipse/buildship#580]
**UPDATE:**

The dialog eventually un-hung and showed me this exception:
```

org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-2.9-bin.zip'.
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:129)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:40)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:50)
	at org.gradle.tooling.internal.consumer.DefaultProjectConnection.getModel(DefaultProjectConnection.java:41)
	at org.eclipse.buildship.core.workspace.internal.ConnectionAwareLauncherProxy.newModelBuilder(ConnectionAwareLauncherProxy.java:64)
	at org.eclipse.buildship.core.workspace.internal.DefaultModelProvider.fetchModel(DefaultModelProvider.java:68)
	at org.eclipse.buildship.core.workspace.internal.DefaultModelProvider.fetchBuildEnvironment(DefaultModelProvider.java:87)
	at org.eclipse.buildship.core.projectimport.ProjectPreviewJob.fetchBuildEnvironment(ProjectPreviewJob.java:81)
	at org.eclipse.buildship.core.projectimport.ProjectPreviewJob.runToolingApiJobInWorkspace(ProjectPreviewJob.java:74)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob$1.run(ToolingApiWorkspaceJob.java:79)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob.runInWorkspace(ToolingApiWorkspaceJob.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/wodencafe/.gradle/wrapper/dists/gradle-2.9-bin/ebaspjjvvkuki3ldbldx7hexd/gradle-2.9-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.tooling.internal.consumer.DistributionInstaller.install(DistributionInstaller.java:73)
	at org.gradle.tooling.internal.consumer.DistributionFactory$ZippedDistribution.getToolingImplementationClasspath(DistributionFactory.java:123)
	at org.gradle.tooling.internal.consumer.loader.CachingToolingImplementationLoader.create(CachingToolingImplementationLoader.java:40)
	at org.gradle.tooling.internal.consumer.loader.SynchronizedToolingImplementationLoader.create(SynchronizedToolingImplementationLoader.java:43)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.onStartAction(LazyConsumerActionExecutor.java:101)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:83)
	at org.gradle.tooling.internal.consumer.connection.CancellableConsumerActionExecutor.run(CancellableConsumerActionExecutor.java:45)
	at org.gradle.tooling.internal.consumer.connection.ProgressLoggingConsumerActionExecutor.run(ProgressLoggingConsumerActionExecutor.java:58)
	at org.gradle.tooling.internal.consumer.connection.RethrowingErrorsConsumerActionExecutor.run(RethrowingErrorsConsumerActionExecutor.java:38)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Still, it would be nice if the dialog told me what it was doing, I had no idea it was trying to download Gradle. 

Also, do you have any idea why it wouldn't be able to retrieve this version of Gradle?

**ORIGINAL MESSAGE:**

Hi guys,

I encountered a hang with Oxygen / Buildship 2.1.2, in which I can't import a Gradle Project with the Buildship Gradle Import Wizard.

First, I downloaded this zip, which contains 2 Gradle Projects: https://bugs.eclipse.org/bugs/attachment.cgi?id=258588

This zip is attached to this bug: Bug 479609 - Buildship should handle duplicate project names across the whole workspace
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479609

This issue I am reporting is a separate problem, in which I can't even import a single project.

I extracted the 2 projects in the Zip to here:
`~/work/
`
So I have:

```
~/work/Gradle Root Project A/
~/work/Gradle Root Project B/
```
In Eclipse, I select Import -> Existing Gradle Project

![screenshot_20170922_113712](https://user-images.githubusercontent.com/31221500/30754988-7f7cc2d8-9f8a-11e7-9a20-37996f907ca2.png)

On the next page, I set the Project Root Directory to:
`/home/wodencafe/work/Gradle Root Project A`
![screenshot_20170922_113731](https://user-images.githubusercontent.com/31221500/30755017-98d15ef6-9f8a-11e7-9386-7bab4901992e.png)

Then I hit next, and next. On the last page, the import hangs:

![screenshot_20170922_113604](https://user-images.githubusercontent.com/31221500/30755031-aa6587fa-9f8a-11e7-90b2-4be067493984.png)

Is this a known issue, or is there anything wrong with the way I am attempting to import this project?

Thank you,

Chris Boyd

**Comment by donat** [comment]
You encountered two Buildship problems at the same time:
 - No progress reported on project preview wizard page: #440
 - Gradle distribution download progress should be visible upon project import #351

The Gradle 2.9 download should work fine. Does your `gradle/wrapper/gradle-wrapper.properties` file specify the standard download URL pointing to 
`services.gradle.org/distributions`?

**Comment by christopherbryanboyd** [comment]
Hi @donat, I think it was the internet connection I was using at the time, that cuased problems with the download. When I tried it from home, it succeeded. So we can probably close this issue, since those other 2 issues already exist :)

**Comment by donat** [comment]
Thanks for the update! I'm closing this issue now.
