### ISSUE TITLE
Bizarre Error when I close Eclipse: org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed

### ISSUE THREAD

**Issue by wodencafe** [eclipse/buildship#583]
When I close Eclipse Oxygen, I receive the following exception in the terminal:
```
Exception in thread "DisconnectableInputStream source reader" Exception in thread "DisconnectableInputStream source reader" Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Input Stream Closed
        at org.eclipse.ui.console.IOConsoleInputStream.available(IOConsoleInputStream.java:268)
        at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:95)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more
org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Input Stream Closed
        at org.eclipse.ui.console.IOConsoleInputStream.available(IOConsoleInputStream.java:268)
        at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:95)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more
org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Input Stream Closed
        at org.eclipse.ui.console.IOConsoleInputStream.available(IOConsoleInputStream.java:268)
        at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:95)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more

```

**Buildship: Eclipse Plug-ins for Gradle	2.1.2.v20170807-1324	org.eclipse.buildship.feature.group	Eclipse Buildship**
**Eclipse IDE for Java Developers**
**Version: Oxygen Release (4.7.0)**
**Build id: 20170620-1800**

**Comment by donat** [comment]
I can reproduce the issue.

**Comment by wrprice** [comment]
May not be strictly Eclipse-related.  I get a similar stack trace on a Win10 command line:

```
BUILD SUCCESSFUL in 4m 12s
38 actionable tasks: 37 executed, 1 up-to-date
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Stream Closed
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.io.IOException: Stream Closed
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:256)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more
```

Environment:

```
------------------------------------------------------------
Gradle 4.2.1
------------------------------------------------------------

Build time:   2017-10-02 15:36:21 UTC
Revision:     a88ebd6be7840c2e59ae4782eb0f27fbe3405ddf

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9 (Oracle Corporation 9+181)
OS:           Windows 10 10.0 amd64
```

**Comment by Vishwa-Kumar** [comment]
yaa it's not eclipse related issue for sure 
as I am getting this on my ubuntu server during gradle clean and gradle build

**Comment by regrog** [comment]
Having the same error here closing eclipse
Eclipse version: 2019-03 (4.11.0)
gradle 5.5.1
JDK 8

```
Caused by: java.io.IOException: Input Stream Closed
	at org.eclipse.ui.console.IOConsoleInputStream.available(IOConsoleInputStream.java:271)
	at org.eclipse.ui.console.IOConsoleInputStream.read(IOConsoleInputStream.java:98)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
	... 1 more
Exception in thread "DisconnectableInputStream source reader" Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: Input Stream Closed
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:61)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Vampire** [comment]
I just refactored a custom task to use the worker api.
Before in the task directly I did use the Gradle AntBuilder.
But as I'm now in the worker I use the Groovy AntBuilder directly.
Now my build also started to show this error, or actually a very similar one:
```
Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.EOFException: No input provided for project
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: No input provided for project
        at org.apache.tools.ant.Project.defaultInput(Project.java:1304)
        at org.apache.tools.ant.Project.demuxInput(Project.java:1324)
        at org.apache.tools.ant.DemuxInputStream.read(DemuxInputStream.java:71)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        ... 1 more
```
