### ISSUE TITLE
Can't create project with target Gradle version <= 2.3

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#607]
If Gradle 2.3 earlier is specified in the new project wizard then the following exception happens.
```
Loading Gradle project preview failed due to an unexpected error.
Unsupported method: GradleEnvironment.getGradleUserHome().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: GradleEnvironment.getGradleUserHome().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
	at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:33)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:359)
	at com.sun.proxy.$Proxy71.getGradleUserHome(Unknown Source)
	at org.eclipse.buildship.core.configuration.GradleArguments.describe(GradleArguments.java:69)
	at org.eclipse.buildship.core.workspace.internal.ConnectionAwareLauncherProxy.applyConfiguration(ConnectionAwareLauncherProxy.java:108)
	at org.eclipse.buildship.core.workspace.internal.ConnectionAwareLauncherProxy.newBuildLauncher(ConnectionAwareLauncherProxy.java:81)
	at org.eclipse.buildship.core.workspace.internal.DefaultGradleBuild.newBuildLauncher(DefaultGradleBuild.java:89)
	at org.eclipse.buildship.ui.wizard.project.ProjectCreationWizard$NewGradleProjectInitializer.run(ProjectCreationWizard.java:284)
	at org.eclipse.buildship.core.projectimport.ProjectPreviewJob.runToolingApiJobInWorkspace(ProjectPreviewJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob$1.run(ToolingApiWorkspaceJob.java:79)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiWorkspaceJob.runInWorkspace(ToolingApiWorkspaceJob.java:76)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

We should investigate the root cause and either fix the problems or at remove unsupported version options from the list.

**Comment by ottoman91** [comment]
has there been any progress on this? I am running into the same error on my buildship, and this is the first time that the error has come up. Its become a hindrance to the point that I have moved onto coding from the CLI until i can find a solution to this.

**Comment by donat** [comment]
We haven't prioritized the fix because the problem is related to a really old Gradle version and because - until now - nobody spoke up, even with a simple 👍. I'll see if I can provide a quick fix.

**Comment by ottoman91** [comment]
thanks! a query. If i upgrade my gradle version, can it have some unintended consequences? ive been using gradle version 1.1 cuz i am reusing the code extensively from a prior project and modifying it to the client's needs, so not sure how it might affect the legacy code base.

**Comment by donat** [comment]
You can jump between target Gradle versions by using the Gradle wrapper. The used artifacts are isolated between versions, although I'm not sure about the old versions like 1.1. If something gets corrupted, you can always get a clean slate by deleting the `.gradle` folder in your project.

**Comment by donat** [comment]
And please, try to upgrade to a more recent version, Gradle improved so much since 1.x :)

**Comment by donat** [comment]
I don't think we'll look into this story anymore. The Tooling API from Gradle 5.0 will support Gradle versions >=2.9 and Buildship has the same [constraint](https://github.com/eclipse/buildship/blob/release-3.0/org.eclipse.buildship.core.test/src/main/groovy/org/eclipse/buildship/core/test/fixtures/GradleVersionParameterization.java#L124) on the development branch.
