### ISSUE TITLE
Refreshing Tasks view may result in `IllegalStateException ` 

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#645]
It looks like that the `ReloadTaskViewRefreshJob` can invoke `TaskView.setContent()` such that it throws an `IllegalStateException`. 

    java.lang.IllegalStateException: Need an underlying widget to be able to set the input.(Has the widget been disposed?)
        at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1687)
        at org.eclipse.buildship.ui.view.task.TaskView.setContent(TaskView.java:189)
        at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob$1.run(ReloadTaskViewJob.java:86)
        at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
        at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4203)

This problem has been reported many times in AERI: 
https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/58354f9ee4b0e5173f296192

**Comment by donat** [comment]
The exception can happen when the viewer's tree widget is either `null` or already disposed. Since the `ReloadTaskViewJob` is created after the tasks view itself, then I think it can be only the latter. 

In `TaskView.setContent()` we do two UI-related things:
``` 
this.pages.showPage((models.isEmpty() && faultyProjects.isEmpty()) ? this.emptyInputPage : this.nonEmptyInputPage);
this.treeViewer.setInput(content);
```
The first statement is a no-op if a target widget is disposed, that's why we fail on the second one.
