### ISSUE TITLE
Buildship doesn't add Junit5 library

### ISSUE THREAD

**Issue by eximius313** [eclipse/buildship#668]
I added:
```
buildscript {
    ext {
        junitVersion = '5.1.0'
    }
}
dependencies {
    testCompile (
        [group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: junitVersion]
    )
    testRuntimeOnly (
        [group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: junitVersion],
    )
}
test {
    useJUnitPlatform()
}

```

to my `build.gradle` and run `Gradle > Refresh Gradle Project`
unfortunately Junit5 library was not added to `Modulepath` and I had to add it manually to my `Java Build Path > Libraries > Modulepath`
A thing to notice is when you add it to `Libraries > Classpath` instead of `Libraries > Modulepath` you get following exception while running Junit:
```
mar 06, 2018 2:37:49 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.SecurityException: class "org.junit.platform.engine.support.filter.ExclusionReasonConsumingFilter"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1141)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:896)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.createTestClassPredicate(VintageDiscoverer.java:83)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:61)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.<init>(JUnit5TestReference.java:42)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:73)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:63)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:50)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

mar 06, 2018 2:37:49 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.SecurityException: class "org.junit.platform.engine.support.filter.ExclusionReasonConsumingFilter"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1141)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:896)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1005)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.createTestClassPredicate(VintageDiscoverer.java:83)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:61)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by oehme** [comment]
> unfortunately Junit5 library was not added to Modulepath

Buildship doesn't use the module path, it uses the classpath. You'll find all your dependencies in the "Project and External dependencies" container.

**Comment by eximius313** [comment]
I should mention that it's JDK9, and adding it to the classpath caused exception.
And without manually adding Junit5, tests didn't run

**Comment by oehme** [comment]
You shouldn't need the JUnit 5 Eclipse library, JUnit 5 should already be in the "Project and External Dependencies".

**Comment by eximius313** [comment]
When I remove it, jupiter libraries are indeed in `Project and External Dependencies`, but when I try to run the test, Eclipse shows:
![image](https://user-images.githubusercontent.com/5578017/37036859-393ecf5c-2151-11e8-8439-28e220c3c520.png)
and then throws:
```
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:31)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:367)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:362)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:306)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:221)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:205)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.core.LauncherFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 11 more
```

**Comment by oehme** [comment]
Looks like this [JDT bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=525948) which was fixed in a recent Eclipse version.

**Comment by eximius313** [comment]
nope
![image](https://user-images.githubusercontent.com/5578017/37039529-016e6ea0-2158-11e8-9098-ceaaddb6bf39.png)

**Comment by eximius313** [comment]
Oh, in [4.7.3](https://www.eclipse.org/eclipse/development/plans/freeze_plan_4_7_3.php) which is not yet released ;(

**Comment by oehme** [comment]
You could try out the nightly to see if it fixes the problem.

**Comment by eximius313** [comment]
I'll see if I can

**Comment by eximius313** [comment]
Unfortunately:
![image](https://user-images.githubusercontent.com/5578017/37769619-dda91fb6-2dd1-11e8-82c8-e9aab752f8da.png)

```
java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:31)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:367)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:362)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:306)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:221)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:205)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.core.LauncherFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 11 more
```

**Comment by d3b5s3r** [comment]
To fix this issue you need to go to the Order and Export section of your export and move the JUnit5 dependency above the Project and External Dependencies library

![junit5](https://user-images.githubusercontent.com/7703109/38165993-ebb3a39e-34e1-11e8-8433-5c8f28ff547c.JPG)

**Comment by eximius313** [comment]
How this could help if Buildship removes the library completly while I do `Gradle > Refresh Gradle project` ?
Of course I tried it:
![image](https://user-images.githubusercontent.com/5578017/38189079-cac69a6e-365e-11e8-8a87-25166e894a87.png)
but the library was removed anyway

**Comment by Hieronymu5** [comment]
You are correct.  It does get removed when you Refresh Gradle.  I was able to resolve it by adding a dependency to the launcher in my gradle build file. (I have junitPlatformVersion is set to 1.1.0)

testCompile("org.junit.platform:junit-platform-launcher:${junitPlatformVersion}")

![junit5-2](https://user-images.githubusercontent.com/7703109/38200559-75307790-365a-11e8-8e41-d0707307b888.JPG)

**Comment by oehme** [comment]
It looks like Eclipse expects your project to provide the `junit-platform-launcher` dependency, which as far as I know is incorrect. Eclipse should contain this dependency itself, not require it as a project library. The launcher is project-independent. Could you open a bug for the JUnit Eclipse plugin?

**Comment by dovogt** [comment]
The problem still exists. Eclipse has its own plugin for Junit. This allows the JUnit tests to be executed in Eclipse and evaluated graphically.

![image](https://user-images.githubusercontent.com/25249296/54192460-4a232800-44b8-11e9-9ffb-6a6802005790.png)

The following entry is added to the .classpath file. This cannot be defined in the dependencies via build.gradle. 

```
	<classpathentry kind="con" path="org.eclipse.jdt.junit.JUNIT_CONTAINER/5">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
```
When refresh gradle is called from the menu, buildship changes the .classpath file and removes the entry for the JUNIT5_CONTAINER.

![image](https://user-images.githubusercontent.com/25249296/54194570-d3d4f480-44bc-11e9-98ae-fefab471077e.png)

I had already reported the problem some time ago
https://discuss.gradle.org/t/refresh-gradle-project-override-classpath/21112/25
