### ISSUE TITLE
buildship 2.2.2 integration test classpath issue

### ISSUE THREAD

**Issue by gadamsciv** [eclipse/buildship#796]
There appears to be a regression issue in buildship 2.2.2 regarding integration testing classpath, specifically when using includeBuild in settings.gradle.

To reproduce, 
git clone https://github.com/gadamsciv/foo-service.git
and 
git clone https://github.com/gadamsciv/foo-model.git
into the same directory. foo-service has a settings.gradle with includeBuild('../foo-model')
with buildship 2.2.1 installed, running /foo-service/src/itest/java/example/foo/model/FooModelIT.java via junit passes with output:

```
classpath: /Users/gadams/git/temp/foo-service/bin/main:/Users/gadams/git/temp/foo-service/bin/test:/Users/gadams/git/temp/foo-service/bin/itest:/foo-model/bin/default:/Users/gadams/git/temp/foo-model/bin/main:/Users/gadams/git/temp/foo-model/bin/test:/Users/gadams/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/gadams/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/3.11.1/fdac3217b804d6900fa3650f17b5cb48e620b140/assertj-core-3.11.1.jar:/Users/gadams/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/gadams/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/410/0/.cp:/Users/gadams/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/409/0/.cp
foo.name: name, foo.bar: 1
```

with buildship 2.2.2 installed, the integration test fails with output

```
classpath: /Users/gadams/git/temp/foo-service/bin/main:/Users/gadams/git/temp/foo-service/bin/test:/Users/gadams/git/temp/foo-service/bin/itest:/foo-model/bin/default:/Users/gadams/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/gadams/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/3.11.1/fdac3217b804d6900fa3650f17b5cb48e620b140/assertj-core-3.11.1.jar:/Users/gadams/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/gadams/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/410/0/.cp:/Users/gadams/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/409/0/.cp
```

and junit failure trace:
```
java.lang.NoClassDefFoundError: example/foo/model/Foo
	at example.foo.model.FooModelIT.constructFoo(FooModelIT.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.lang.ClassNotFoundException: example.foo.model.Foo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

note that in the buildship 2.2.2 failure case, classpath is missing /Users/gadams/git/temp/foo-model/bin/main

**Comment by clo-vis** [comment]
Also in buildship 3.0.0 (shipped with Eclipse 2018-12)

**Comment by Kameecoding** [comment]
Any update on this issue?
