### ISSUE TITLE
Output location update should not try to use nested locations

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#811]
[Bugzilla report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=541571):
> Buildship Gradle feature version 2.2.1
> 
> Clone git repo: https://github.com/spring-io/sagan
> Comment out everything from `sagan-client/build.gradle` such that its contents is only :
> apply plugin: 'java'
> (The build may get stuck at npm install bit to avoid that comment this part out)
> 
> Now run `gradle build clean` from the CLI. Should work.
> 
> Import the project via Gradle -> Existing Gradle Project...
>
> The operation fails with:
>
> Java Model Exception: Java Model Status [Cannot nest output folder 'sagan-common/bin/main' inside output folder 'sagan-common/bin']
>	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:798)
>	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3559)
>      ...

**Comment by donat** [comment]
The output and the source folder updater should not try to use nested output folders. If the update leads to this situation then the updaters should use a temporary folder. If the configuration is invalid, the synchronization should throw an `UnsupportedConfigurationException`.

**Comment by donat** [comment]
The problem has a workaround: define a separate output folder manually, then synchronize the workspace with the Gradle build.

**Comment by BoykoAlex** [comment]
@donat can you propose a way to fix the the gradle build please? :-)

**Comment by donat** [comment]
The weird thing is that the exception happened only the first time. Afterward, I was able to import the projects no matter what Gradle versions I chose or how I cleaned up the project. I'll get back to this later.

**Comment by BoykoAlex** [comment]
@donat You mentioned there is a workaround. How can I apply the workaround? I suppose the workaround can be done in `build.gradle` files somewhere?
