### ISSUE TITLE
Buildship should not try to import builds with sub-projects sharing the same directory

### ISSUE THREAD

**Issue by pac0rro** [eclipse/buildship#822]
Hi, 

I have about twenty projects configured with gradle composite builds. Building an EAR for the project with command line gradle works fine. But I have problems when I import them into eclipse and I submit a **Gradle Refresh**.  It hangs at 35% progress. I have added -d flag (eclipse preferences) and I see:

`16:15:01.454 [LIFECYCLE] [org.gradle.launcher.daemon.server.Daemon] 
16:15:01.454 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:15:01.454 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:01.455 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:01.455 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:01.455 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:01.456 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:01.456 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:11.452 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:15:11.452 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:11.453 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:11.453 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:11.456 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:11.456 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:11.457 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:21.451 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
16:15:21.452 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:21.452 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:21.453 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:21.453 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
16:15:21.454 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
16:15:21.455 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
16:15:31.446 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running`

I created also a thread dump and heap dump from the daemon java process. I Attach only the thread dump.

[threaddump-1544443717363.zip](https://github.com/eclipse/buildship/files/2663825/threaddump-1544443717363.zip)

Thank you.

**Comment by pac0rro** [comment]
I've found that for three small related projects I got eclipse error markers:
"Cannot Query Eclipse model"

![image](https://user-images.githubusercontent.com/604217/49748123-2ed03300-fca5-11e8-881b-6634c0005d2b.png)

**Comment by donat** [comment]
Can you please paste the stack trace here? To reveal it, right-click on the error marker and select `Properties`.

**Comment by pac0rro** [comment]
java.lang.IllegalStateException: Duplicate key org.eclipse.buildship.core.internal.util.gradle.CompatEclipseProject@7cbaff02
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.buildship.core.internal.workspace.BaseConfigurator.init(BaseConfigurator.java:51)
	at org.eclipse.buildship.core.internal.extension.InternalProjectConfigurator.init(InternalProjectConfigurator.java:59)
	at org.eclipse.buildship.core.internal.workspace.ProjectConfigurators.initConfigurators(ProjectConfigurators.java:48)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:76)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:67)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.runInToolingApi(DefaultGradleBuild.java:221)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:182)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:95)
	at org.eclipse.buildship.core.internal.workspace.SynchronizationJob.runInToolingApi(SynchronizationJob.java:63)
	at org.eclipse.buildship.core.internal.workspace.SynchronizationJob.runInToolingApi(SynchronizationJob.java:29)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob$1.runInToolingApi(ToolingApiJob.java:53)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob.run(ToolingApiJob.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)

**Comment by pac0rro** [comment]
This is the stacktrace for "failed to configure project ..." error maker:
`java.lang.NullPointerException
	at org.eclipse.buildship.core.internal.workspace.BaseConfigurator.lookupEclipseModel(BaseConfigurator.java:125)
	at org.eclipse.buildship.core.internal.workspace.BaseConfigurator.configure(BaseConfigurator.java:72)
	at org.eclipse.buildship.core.internal.workspace.BaseConfigurator.configure(BaseConfigurator.java:61)
	at org.eclipse.buildship.core.internal.extension.InternalProjectConfigurator.configure(InternalProjectConfigurator.java:64)
	at org.eclipse.buildship.core.internal.workspace.ProjectConfigurators.configureConfigurators(ProjectConfigurators.java:67)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:166)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.synchronizeWorkspaceProject(SynchronizeGradleBuildOperation.java:140)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:130)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:45)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:88)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2311)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:85)
	at org.eclipse.buildship.core.internal.workspace.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:67)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.runInToolingApi(DefaultGradleBuild.java:221)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:182)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:95)
	at org.eclipse.buildship.core.internal.workspace.SynchronizationJob.runInToolingApi(SynchronizationJob.java:63)
	at org.eclipse.buildship.core.internal.workspace.SynchronizationJob.runInToolingApi(SynchronizationJob.java:29)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob$1.runInToolingApi(ToolingApiJob.java:53)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob.run(ToolingApiJob.java:64)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)`

**Comment by donat** [comment]
Your build contains multiple projects that share the same project directory. This use case is not illegal in Gradle. However, Buildship does not cover it. You can works around this by using unique project directories in your build. I'll look into fixing this.

**Comment by pac0rro** [comment]
Thank you, Donat. 
I don't understand what you are saying. Indeed, there is only one project inside a directory.
The project structure is:
`
asd ada
da
d
asd
ads
`

**Comment by donat** [comment]
Let me illustrate it with an example. Consider the following `settings.gradle` file:
```
include('sub1')
include('sub2')

def sub1 = rootProject.children.find { it.name == 'sub1' }
def sub2 = rootProject.children.find { it.name == 'sub2' }

sub1.projectDir = file('subproject') // <-- same location
sub1.buildFileName = 'build1.gradle'

sub2.projectDir = file('subproject') // <-- same location
sub2.buildFileName = 'build2.gradle'
```

This is technically valid (but it shouldn't be IMHO).  Also, you can't import it in Buildship and produces the same stack trace you provided.

I'm still yet to find out how it can happen with included builds.

**Comment by pac0rro** [comment]
Ok, It's not the same case, but produces the same exception. I paste here some `settings.gradle`:

```
rootProject.name='KafkaProxyServerExecutor'
  
includeBuild '../SimpleTCPCommunications'
includeBuild '../KafkaProxy'
```

```
rootProject.name='KafkaProxy'
includeBuild '../SimpleTCPCommunications'
```

```
rootProject.name='SimpleTCPCommunications'
```

**Comment by donat** [comment]
> This behaviour did appear with Buildship 3.

Buildship 3.0 only exposed the problem, it was there before too. In 2.0 the overlapping project was configured twice.

> I paste here some settings.gradle files:

Would it fix your IDE setup if you removed the `includeBuild '../SimpleTCPCommunications'` entry from `KafkaProxy`?

**Comment by pac0rro** [comment]
I will test it

**Comment by pac0rro** [comment]
Donat, it seems you have implemented this feature. What is the roadmap for Buildship 3.0.1?

Probably this fix, solves the following issues:
1. Error marker 'eclipse model not found'
2. Duplicated projects on Gradle Tasks
3. Eclipse / daemon hanging when doing Gradle Refresh
What do you think?
Thank you!!!

**Comment by donat** [comment]
I'm about to publish a milestone release which I recommend you to install.
Regarding the duplicates, it seems that it's a bug in Gradle itself. I'll go investigate.

**Comment by donat** [comment]
I agree that it doesn't make sense to list all the project names in the exception message. I already [fixed](https://github.com/eclipse/buildship/commit/f9d0ea5b7c0aa27483767c1a9ff1817331bcf4da) it. On the other hand, your project setup shouldn't even be valid. Composite builds are to allow developers to work on projects that are maintained independently. My suggestion is to refactor your build such that all `includeBuild` statement is placed in one file, probably in `ProjectA`. If it's not possible, then you probably want to convert your build to a plain multi-project build (i.e., replace `includeBuild` statements with `include`).

**Comment by pac0rro** [comment]
> Composite builds are to allow developers to work on projects that are maintained independently

Umm... it seems gradle allows this behaviour:

> Composite builds allow you to:
> - combine builds that are usually developed independently, for instance when trying out a bug fix in a library that your application uses
>  - decompose a large multi-project build into smaller, more isolated chunks that can be **worked in independently or together as needed**


> My suggestion is to refactor your build such that all includeBuild statement is placed in one file, probably in ProjectA

This situation defeats the purpose of isolation, independent builds. Every project has to be independent. 

>  If it's not possible, then you probably want to convert your build to a plain multi-project build (i.e., replace includeBuild statements with include).

This is correct for a large number of projects, but Composite Builds came to cover this need and help special projects that are difficult to maintain with plain multi-project builds.

What I 'm missing is that:
- Command line Gradle v4 and v5 build perfectly with my gradle scripts
- Buildship 2.x also had no problem with that on my case (that three projects)
- Intellij also build successfully that three projects

I think that your issue to Gradle team (#8031) will not succeed because right now many people are running projects with this simple build disposition:  A -> B and C,   B->C,    C
... and if Gradle team implements that validation, many gradle users will be affected.

**Comment by pac0rro** [comment]
Right now I am switching my projects to eclipse based projects (no maven / gradle builds).
But in the near future I will try to create a "tryIncludeBuild" groovy function to check if the build ProjectC has been included already. Thus, I will call:

tryIncludeBuild '../ProjectC'

But probably I will have a lot of problems with that approach, I think.

**Comment by jetklok** [comment]
@donat, will this use case (importing a build multiple times) be supported by Buildship in the future?

**Comment by donat** [comment]
@jetklok I don't think this will happen any time soon. Buildship even has a requirement that all project names in the Gradle build must be free in the workspace. We need to eliminate this constraint before we can consider the feature you mentioned.

**Comment by clemensdev** [comment]
> What I 'm missing is that:
>     * Command line Gradle v4 and v5 build perfectly with my gradle scripts
>     * Buildship 2.x also had no problem with that on my case (that three projects)
>     * Intellij also build successfully that three projects
> 
> I think that your issue to Gradle team (#8031) will not succeed because right now many people are running projects with this simple build disposition: A -> B and C, B->C, C
> ... and if Gradle team implements that validation, many gradle users will be affected.
we, being one of "these affected", completely agree with @pac0rro 's points and missings.

>Buildship 2.x also had no problem with that on my case (that three projects)
@pac0rro does 2.* still work "as expected". What features/critical bugfixes of 3.* will we be missing in the old 2.*?

**Comment by deanorderly** [comment]
More and more people are creating mono-repos and mono-builds.  We definitely need the above to work.  We have 11 micro services and 7 libraries and ONLY bring in each microservice as a composite build so when you load it, it loads ALL source for all libraries in the mono-repo so you can work on the service and library together.  

NOT ONLY that, it goes further, in mono-repo form, I may have svcA, libB, libC BUT I may then ADD svcX which also uses libB so I can refactor method G and both svcA and svcX will be refactored.  Currently, we work in intellij but can't seem to get our stuff to work in eclipse anymore so it's become a bit more dead to us :( and I LOVE the eclipse debugger(the intellij one sucks).

**Comment by donat** [comment]
> @jetklok I don't think this will happen any time soon. Buildship even has a requirement that all project names in the Gradle build must be free in the workspace. We need to eliminate this constraint before we can consider the feature you mentioned.


FYI this is no longer true. If you use a more recent version of Eclipse/Buildship then the overlapping project names will be properly deduplicated.

**Comment by donat** [comment]
Isse for multi-composite support here: https://github.com/eclipse/buildship/issues/908
