### ISSUE TITLE
Synchronization fails in Buildship

### ISSUE THREAD

**Issue by cdietrich** [eclipse/buildship#846]
we have something like this in our buildscript

```
buildscript {
	apply from: "${rootDir}/gradle/versions.gradle"
	repositories {
		maven{
			url "$rootDir/build2/maven-repository"
		}
		jcenter()
	}
	dependencies {
		classpath "org.xtext:xtext-gradle-plugin:$versions.xtext_gradle_plugin"
	}
}
......
subprojects {
	version = rootProject.version
	
	repositories {
		maven{
			url "$rootDir/build2/maven-repository"
		}
		jcenter()
	}
	
	apply plugin: 'java'
....
```

this works fine from command line but with buildship it fails with

```
Searched in the following locations:
  - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/maven-metadata.xml
  - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.pom
  - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.jar
  - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/maven-metadata.xml
  - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.pom
Required by:
    project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib
    project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtext.xbase.lib
    project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtend.lib.macro
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(DefaultBuildableComponentResolveResult.java:42)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:108)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMetaDataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.ComponentResolversChain$ComponentMetaDataResolverChain.resolve(ComponentResolversChain.java:95)
	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resolve(ClientModuleResolver.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.resolve(ComponentState.java:199)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.ComponentState.getMetadata(ComponentState.java:152)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.calculateTargetConfigurations(EdgeState.java:173)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.EdgeState.attachToTargetConfigurations(EdgeState.java:129)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.attachToTargetRevisionsSerially(DependencyGraphBuilder.java:316)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolveEdges(DependencyGraphBuilder.java:215)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.traverseGraph(DependencyGraphBuilder.java:168)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.builder.DependencyGraphBuilder.resolve(DependencyGraphBuilder.java:129)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultArtifactDependencyResolver.resolve(DefaultArtifactDependencyResolver.java:121)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolveGraph(DefaultConfigurationResolver.java:169)
	at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveGraph(ShortCircuitEmptyConfigurationResolver.java:86)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveGraph(ErrorHandlingConfigurationResolver.java:73)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$7.run(DefaultConfiguration.java:566)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:555)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$600(DefaultConfiguration.java:127)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$6.run(DefaultConfiguration.java:538)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry$SafeExclusiveLockImpl.withLock(DefaultProjectStateRegistry.java:244)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveExclusively(DefaultConfiguration.java:534)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:529)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2100(DefaultConfiguration.java:127)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getSelectedArtifacts(DefaultConfiguration.java:1095)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.access$3400(DefaultConfiguration.java:1030)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationArtifactCollection.ensureResolved(DefaultConfiguration.java:1554)
	... 138 more
```

why is the local build2 repo not searched? do i miss something?

**Comment by cdietrich** [comment]
problem seems to be related to composite builds

**Comment by cdietrich** [comment]
can reproduce this with pure gradle too. will open gradle bug
