### ISSUE TITLE
Import wizzard fails to import Gradle project with: Project 'XYZ' is not open

### ISSUE THREAD

**Issue by januhlir** [eclipse/buildship#868]
Here are is complete source code of my trivial project, it has two sub-projects, all very standard:
https://bitbucket.org/espinosa/spring-integration-tcp-demo/src/master/

I managed successfully opened it once and it worked for a while. But then I tried to rename the two sub-projects, using refactor -> rename - it failed horribly. So I did all changes manually, renamed directories, modified `settings.gradle` with new names, etc. Then I cleaned up all Eclipse `.settings`, `.project` and `.classpath`, plus all `.gradle`, `build` and `bin` directories. 

The intention was to load project again, from scratch. Interestingly, it is not possible anymore.
The Finish button of the import wizard doesn't do anything and in logs I found 1 error and coupel of (same) warnings.  

Error: Project 'z062-spring-integration-tcp-demo' is not open.

```` 
java.lang.Exception: Project 'z062-spring-integration-tcp-demo' is not open.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:148)
	at org.eclipse.core.internal.resources.Resource.createMarker(Resource.java:688)
	at org.eclipse.buildship.core.internal.marker.GradleErrorMarker.createMarker(GradleErrorMarker.java:49)
	at org.eclipse.buildship.core.internal.marker.GradleErrorMarker.createError(GradleErrorMarker.java:40)
	at org.eclipse.buildship.core.internal.marker.GradleMarkerManager.addError(GradleMarkerManager.java:73)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:194)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:95)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectImportWizardController$5.run(ProjectImportWizardController.java:215)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
````

Warning: Synchronize project z062-spring-integration-tcp-demo failed due to an error while importing the root project.

````
org.eclipse.buildship.core.internal.ImportRootProjectException: org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Cannot add nature org.eclipse.buildship.core.gradleprojectnature to Eclipse project z062-spring-integration-tcp-demo.
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.run(ImportRootProjectOperation.java:52)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.runInToolingApi(DefaultGradleBuild.java:216)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:57)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:38)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild$SynchronizeOperation.run(DefaultGradleBuild.java:182)
	at org.eclipse.buildship.core.internal.DefaultGradleBuild.synchronize(DefaultGradleBuild.java:95)
	at org.eclipse.buildship.ui.internal.wizard.project.ProjectImportWizardController$5.run(ProjectImportWizardController.java:215)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Cannot add nature org.eclipse.buildship.core.gradleprojectnature to Eclipse project z062-spring-integration-tcp-demo.
	at org.eclipse.buildship.core.internal.workspace.DefaultWorkspaceOperations.addNature(DefaultWorkspaceOperations.java:232)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.importRootProject(ImportRootProjectOperation.java:100)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.access$300(ImportRootProjectOperation.java:38)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation$1.run(ImportRootProjectOperation.java:68)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.runInWorkspace(ImportRootProjectOperation.java:57)
	at org.eclipse.buildship.core.internal.workspace.ImportRootProjectOperation.run(ImportRootProjectOperation.java:50)
	... 9 more
Caused by: org.eclipse.core.internal.resources.ResourceException: Project 'z062-spring-integration-tcp-demo' is not open.
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:148)
	at org.eclipse.core.internal.resources.Project.getDescription(Project.java:393)
	at org.eclipse.buildship.core.internal.workspace.DefaultWorkspaceOperations.addNature(DefaultWorkspaceOperations.java:211)
	... 16 more
````

**Comment by januhlir** [comment]
Workaround: delete workspace `.metadata` dir which is, huh, quite brutal method.

**Comment by donat** [comment]
Buildship uses the build script configuration as a single source of truth. If you want to rename your project you need to change the build script. You can either modify them in the `settings.gradle` file or, if you want to only modify the eclipse project names, then use the following snippet:
```
plugins {
  id 'eclipse'
}

eclipse {
    project {
        name = 'custom-project-name'
    }
}
```

**Comment by donat** [comment]
Renaming does not work currently, although I have a few ideas on how to fix it.
