### ISSUE TITLE
builds.gradle.org:8000/eclipse/update-site/mirror/releases-rolling/content.jar not availble

### ISSUE THREAD

**Issue by cdietrich** [eclipse/buildship#902]
when i build buildship locally it tries to download the target platform from builds.gradle.org:8000/eclipse/update-site/mirror/releases-rolling/content.jar etc which is sometimes not available / timeouts

**Comment by cdietrich** [comment]
```
!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1002 
2019-07-15 13:00:42.482
!MESSAGE Unable to read repository at http://builds.gradle.org:8000/eclipse/update-site/mirror/releases-rolling/artifacts.xml.

!STACK 
0
org.apache.http.conn.ConnectTimeoutException: Connect to builds.gradle.org:8000 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
        at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)


!ENTRY 
org.eclipse.equinox.p2.transport.ecf 4 1002 2019-07-15 13:06:42.720
!MESSAGE Unable to read repository at http://builds.gradle.org:8000/eclipse/update-site/mirror/orbit-rolling/artifacts.xml.

!STACK 
0
org.apache.http.conn.ConnectTimeoutException: Connect to builds.gradle.org:8000 timed out
        at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
        at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

**Comment by cdietrich** [comment]
now i am getting

```
!ENTRY org.eclipse.equinox.p2.artifact.repository 
4 1000 
2019-07-15 14:51:08.384

!MESSAGE 
No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/releases-rolling/.


!ENTRY 
org.eclipse.equinox.p2.artifact.repository 4 1000 2019-07-15 14:51:08.599
!MESSAGE No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/orbit-rolling/.


!ENTRY org.eclipse.equinox.p2.artifact.repository 4 1000 
2019-07-15 14:51:08.800
!MESSAGE No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/swtbot/release/.


!ENTRY org.eclipse.equinox.p2.metadata.repository 
4 1000 2019-07-15 14:51:09.018

!MESSAGE No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/releases-rolling/.


!ENTRY org.eclipse.equinox.p2.metadata.repository 4
 1000 2019-07-15 14:51:09.207
!MESSAGE No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/orbit-rolling/.


!ENTRY org.eclipse.equinox.p2.metadata.repository 
4 1000 2019-07-15 14:51:09.408
!MESSAGE No repository found at http://builds.gradle.org:8000/eclipse/update-site/mirror/swtbot/release/.

Installation failed.
```

**Comment by donat** [comment]
This was a side-effect of maintenance we've done over the weekend. I'm working on it.

**Comment by donat** [comment]
@cdietrich I've adjusted the update sites. Can you please check if it works for you?

**Comment by cdietrich** [comment]
thanks @donat it is working now
