### ISSUE TITLE
Getting error running Spring boot ApplicationMain.Java 

### ISSUE THREAD

**Issue by gsinghab2** [eclipse/buildship#925]
I am using following versions
Gradle 5.6.2
JDK 11.0.1
Spring Boot 2.1.8.RELEASE
Eclipse: 2019-09 R (4.13.0)

When running SpringBoot main class as Java application I am getting following error.

ENTRY org.eclipse.jdt.core 4 0 2019-09-26 22:16:17.820
!MESSAGE Unexpected internal error
!STACK 1
Java Model Exception: Java Model Status [module-info.class [in <default> [in ...\.gradle\caches\modules-2\files-2.1\org.glassfish.hk2.external\asm-all-repackaged\2.5.0-b42\3afd5d4f63116e8c00b430f32092282e5e475ce8\asm-all-repackaged-2.5.0-b42.jar]] does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.ModularClassFile.getModule(ModularClassFile.java:300)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getSourceModuleDescription(PackageFragmentRoot.java:914)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getModuleDescription(PackageFragmentRoot.java:890)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.getModuleDescription(JarPackageFragmentRoot.java:321)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.addModuleClassPathInfo(JavaSearchNameEnvironment.java:194)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.mapToClassPathLocation(JavaSearchNameEnvironment.java:188)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.computeClasspathLocations(JavaSearchNameEnvironment.java:133)
	at org.eclipse.jdt.internal.core.search.matching.JavaSearchNameEnvironment.<init>(JavaSearchNameEnvironment.java:77)
	at org.eclipse.jdt.internal.core.search.matching.IndexBasedJavaSearchEnvironment.create(IndexBasedJavaSearchEnvironment.java:334)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.initialize(MatchLocator.java:1222)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1260)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1373)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1515)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:112)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.debug.ui.launcher.MainMethodSearchEngine.searchMainMethods(MainMethodSearchEngine.java:97)
	at org.eclipse.jdt.internal.debug.ui.launcher.MainMethodSearchEngine$1.run(MainMethodSearchEngine.java:166)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2019-09-26 22:16:17.820
!MESSAGE module-info.class [in <default> [in ...\.gradle\caches\modules-2\files-2.1\org.glassfish.hk2.external\asm-all-repackaged\2.5.0-b42\3afd5d4f63116e8c00b430f32092282e5e475ce8\asm-all-repackaged-2.5.0-b42.jar]] does not exist

!ENTRY org.eclipse.core.jobs 4 2 2019-09-26 22:16:18.294
!MESSAGE An internal error occurred during: "Launching ApiApplication".
!STACK 0
org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Model not available for Calendar
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:76)
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:55)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1266)
	at org.eclipse.jdt.launching.StandardClasspathProvider.resolveClasspath(StandardClasspathProvider.java:95)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1657)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspath(AbstractJavaLaunchConfigurationDelegate.java:431)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.getVMRunnerConfiguration(JavaLaunchDelegate.java:96)
	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:153)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by jovechina** [comment]
same issue with me. 
fixed after run two command.
```
gradle cleaneclipse
gradle eclipse 
```

**Comment by donat** [comment]
This can only happen when the project synchronization metadata is missing. It can happen if:
- the project was never imported with the Import Gradle Project wizard
- The project was never synchronized (right-click on the project > Gradle > Synchronize)
- someone deleted the Buildship metadata from `${workspace_loc}/.metadata/.plugins/org.eclipse.buildship.core`.

This seems this issue is temporary/environmental, so I'm closing it. Let me know if it happens again.

**Comment by donat** [comment]
Also, don't use the `cleaneclipse` and `eclipse` tasks with Buildship, they are mutually exclusive.
