### ISSUE TITLE
Internal error: Model not available for <project>

### ISSUE THREAD

**Issue by akarnokd** [eclipse/buildship#943]
I'm using Eclipse IDE for Enterprise Java Developers (Version: 2019-09 R (4.13.0), Build id: 20190917-1200) with Buildship plugin (3.1.2.v20190903-1802). Windows 10 x64.

I've upgraded some of my projects to Gradle 6 (first time the machine had Gradle 6), closed them, then opened a Gradle 5.6 project ([RxJava 3.x branch](https://github.com/ReactiveX/RxJava)). For some reason, using the "Run As > JUnit Test" stopped working and gives me this error in the log:

```
!ENTRY org.eclipse.core.jobs 4 2 2019-11-12 12:56:32.209
!MESSAGE An internal error occurred during: "Launching io.reactivex.rxjava3.validators".
!STACK 0
org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Model not available for rxjava
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:76)
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:55)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1266)
	at org.eclipse.jdt.internal.launching.DefaultEntryResolver.resolveRuntimeClasspathEntry(DefaultEntryResolver.java:43)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1282)
	at org.eclipse.jdt.launching.StandardClasspathProvider.resolveClasspath(StandardClasspathProvider.java:95)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1690)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:463)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getClasspathAndModulepath(JUnitLaunchConfigurationDelegate.java:627)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.getVMRunnerConfiguration(JUnitLaunchConfigurationDelegate.java:196)
	at org.eclipse.jdt.junit.launcher.JUnitLaunchConfigurationDelegate.launch(JUnitLaunchConfigurationDelegate.java:257)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Eclipse is set to use the project's wrapper by default, thus the 5.6. 

I've restarted Eclipse, deleted and reimported said project from scratch, deleted the `.gradle` folder and reimported. Same results. "Refresh Gradle Project" succeeds and the log contains no errors.

In comparison, all other projects I upgraded to Gradle 6 work correctly with "Run As > JUnit test" respectively. (Before you ask, upgrading RxJava to Gradle 6 is currently not an option.)

There were no such problems yesterday with the very same setup. The only change today was the introduction of Gradle 6 to unrelated projects.

Is this a bug with Buildship, Gradle 5.6 or Eclipse? Is there a setting I should try and clear?

**Comment by pdkovacs** [comment]
Does this help: https://stackoverflow.com/a/59251711/1194266 ? (It helped me, but I haven't really spent time checking whether your environment matches mine or not, sorry.)

**Comment by akarnokd** [comment]
I upgraded the 5.6 project to 5.6.4 and the issue went away.
