### ISSUE TITLE
Running Eclipse 4.14 with JDK13 make Buildship break

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/buildship#960]
Freshly installed Eclipse 4.14, and JDK 13 the only Java on the system.

I importeted a project, in this case a Gradle plugin project (not sure if this is needed to reproduce).
https://github.com/diffplug/goomph.git

When running Gradle -> Refresh, i get this console output:
````
FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Tools\Eclipse_4.14\workspace\.metadata\.plugins\org.eclipse.buildship.core\init.d\eclipsePlugin.gradle'

* What went wrong:
Could not compile initialization script 'C:\Tools\Eclipse_4.14\workspace\.metadata\.plugins\org.eclipse.buildship.core\init.d\eclipsePlugin.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57
  
  java.lang.IllegalArgumentException: Unsupported class file major version 57
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:184)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:152)
  	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:273)
  	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
  	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:254)
  	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:192)
  	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:172)
  	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:128)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClassNullable(AsmReferenceResolver.java:59)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveClass(AsmReferenceResolver.java:46)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveNonArrayType(AsmReferenceResolver.java:81)
  	at org.codehaus.groovy.ast.decompiled.AsmReferenceResolver.resolveType(AsmReferenceResolver.java:72)
  	at org.codehaus.groovy.ast.decompiled.MemberSignatureParser.createMethodNode(MemberSignatureParser.java:55)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.lazyInitMembers(DecompiledClassNode.java:195)
  	at org.codehaus.groovy.ast.decompiled.DecompiledClassNode.getDeclaredMethods(DecompiledClassNode.java:121)
  	at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:912)
  	at org.codehaus.groovy.ast.ClassNode.tryFindPossibleMethod(ClassNode.java:1280)
  	at org.codehaus.groovy.control.StaticImportVisitor.transformMethodCallExpression(StaticImportVisitor.java:252)
  	at org.codehaus.groovy.control.StaticImportVisitor.transform(StaticImportVisitor.java:112)
  	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:144)
  	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:42)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:110)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:121)
  	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:55)
  	at org.codehaus.groovy.control.StaticImportVisitor.visitConstructorOrMethod(StaticImportVisitor.java:88)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructor(ClassCodeVisitorSupport.java:128)
  	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1099)
  	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:54)
  	at org.codehaus.groovy.control.StaticImportVisitor.visitClass(StaticImportVisitor.java:82)
  	at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:717)
  	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1095)
  	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:649)
  	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:627)
  	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:604)
  	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
  	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
  	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
  	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)

````

I tried as well to set the projects Java compiler version to 8, but this did not help.
I suspect the used groovyjarjarasm is not Java13 ready?

After installing Java 8 and running Eclipse with it, it imports without such errors.

Frank

**Comment by frankbenoit** [comment]
Having Eclipse running on older JVM is not a general workaround, as there are other plugins that require the newer.
E.g. WindowBuilder requires Eclipse running on Java13 when the project uses Java13.

**Comment by donat** [comment]
You are correct, it would be better if Buildship (and other IDEs) could specify the JVM to invoke Gradle. This is a limitation of the Tooling API Gradle submodule.

In your specific case, the problem can be solved easily. The build uses Gradle 5.6 which doesn't support Java 13. You only need to update the wrapper to use Gradle 6.0+ (or change the import settings to use Gradle 6.0+ in Buildship) and then the problem should disappear.
